(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-8',
          componentName:'CookieBanner',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"preset":"footer1","staticContent":{"YouTube":"YouTube Social Link","Facebook":"Facebook Social Link","acceptAndClose":"Accept & Close","Xing":"Xing Social Link","Houzz":"Houzz Social Link","Yelp":"Yelp Social Link","usingCookieTitle":"This website is using cookies.","Google+":"Google Plus Social Link","Instagram":"Instagram Social Link","Twitter":"Twitter Social Link","cookiePolicy":"Cookie Policy","decline":"Decline","Pinterest":"Pinterest Social Link","LinkedIn":"LinkedIn Social Link","usingCookieMessage":"We use them to give you the best experience. If you continue using our website, we'll assume that you are happy to receive all cookies on this website."},"pages":[{"isFlyoutMenu":false,"active":false,"pageId":"b5759c33-70cb-4101-91f4-748f575c5d86","name":"Privacy Policy","href":"\u002Fprivacy-policy","target":"","visible":false,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":true},{"isFlyoutMenu":false,"active":false,"pageId":"ebdccae4-cf12-406e-8c79-2c3e322d9bcc","name":"Terms and Conditions","href":"\u002Fterms-and-conditions","target":"","visible":false,"requiresAuth":false,"tags":[],"rel":"","type":"page","showInFooter":true}],"copyright":"Copyright © 2020 Koramangala Methodist Church - All Rights Reserved.","poweredBy":"Powered by GoDaddy Website Builder","isAccountFree":false,"appName":"Website Builder","cookieBannerEnabled":false,"cookieBannerMessage":"{\"blocks\":[{\"key\":\"688aj\",\"text\":\"This website uses cookies. By continuing to use this site, you accept our use of cookies.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[{\"offset\":0,\"length\":0,\"key\":\"link\"}],\"data\":{}}],\"entityMap\":{\"link\":{\"type\":\"LINK\",\"mutability\":\"MUTABLE\",\"data\":{\"url\":\"\"}}}}","cookieBannerTitle":"Cookie Policy","cookieBannerButtonLabel":"Accept & Close","cookieBannerDeclineEnabled":null,"cookieBannerDeclineLabel":"Decline","isReseller":false,"market":"en-IN","rootDomain":"godaddy.com","planUpgradeLink":"https:\u002F\u002Fwww.godaddy.com\u002Fwebsites\u002Fwebsite-builder?isc=ISC#pricing","socialAccountsEnabled":true,"facebookProfile":null,"twitterProfile":null,"instagramProfile":null,"pinterestProfile":null,"linkedinProfile":null,"youtubeProfile":null,"yelpProfile":null,"houzzProfile":null,"xingProfile":null,"editingCookieBanner":false,"id":"banner-814b4be4-c186-497b-9a5f-807bb9546016","widgetId":"814b4be4-c186-497b-9a5f-807bb9546016","section":"alt","category":"accent","locale":"en-IN","renderMode":"PUBLISH"},{"widgetId":"814b4be4-c186-497b-9a5f-807bb9546016","widgetType":"FOOTER","widgetPreset":"footer1","order":5,"section":"alt","category":"accent","fontSize":"medium","fontFamily":"alternate","group":"Section","groupType":"Default","themeOverrides":{}});